# Generated by Django 5.2 on 2025-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauranteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(choices=[('tapa', 'Tapa'), ('principal', 'Plato principal'), ('postre', 'Postre'), ('bebida', 'Bebida')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
