# Generated by Django 5.2 on 2025-04-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauranteapp', '0002_plato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='disponible',
        ),
    ]
